numGames:              4
generateChunksPerTick: 3
nothingButKiller:      false
defaultGameMode:       Killer_on_the_Loose
defaultWorldGen:       Default_World
killerWorldNamePrefix: killer
filterChat:            true
filterScoreboard:      true
allowSpectators:       true
allowLateJoiners:      true
allowPlayerLimits:     true
