numGames:              4
nothingButKiller:      false
killerWorldNamePrefix: killer
filterChat:            true
filterScoreboard:      true
allowSpectators:       true
allowLateJoiners:      true
allowPlayerLimits:     true
