name: Killer Minecraft
main: com.ftwinston.KillerMinecraft.KillerMinecraft
version: 0.4
load: STARTUP
description: A plugin for managing PVP game modes played out on temporary worlds that are automatically deleted afterwards.
authors: [FTWinston, Canazza]
commands:
  spec:
    usage: As a spectator, use to teleport to other players, or between worlds; /spec <player>, /spec nether or /spec main
  vote:
    usage: Shows a menu that allows you to set up a vote among all players
  team:
    usage: Send a message only to team members, in game modes with teams
  killer:
    usage: Various commands for joining, leaving and configuring games
  help:
    usage: Shows information about the current game mode.