name: Killer
main: com.ftwinston.Killer.Killer
version: 0.3
load: STARTUP
description: Several PVP game modes that focus on subtlety. Features a staging world that lets you set up games to be played on new worlds, automatically deletes these worlds afterwards.
authors: [FTWinston, Canazza]
commands:
  spec:
    usage: As a spectator, use to teleport to other players, or between worlds; /spec <player>, /spec nether or /spec main
  vote:
    usage: Shows a menu that allows you to set up a vote among all players
  team:
    usage: Send a message only to team members, in game modes other than Mystery Killer and Contract Killer
  killer:
    usage: Admin commands to change the killer & restart the game. Only usable by op / console.
  help:
    usage: Shows information about the current game mode.